# coding: utf-8

"""
    Unique ID

    API to look up or generate a unique study identifier

    OpenAPI spec version: 1.0.0
    Contact: scweber@stanford.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.valid_mrn import ValidMrn


class TestValidMrn(unittest.TestCase):
    """ ValidMrn unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValidMrn(self):
        """
        Test ValidMrn
        """
        model = swagger_client.models.valid_mrn.ValidMrn()


if __name__ == '__main__':
    unittest.main()
